title: "FluenteMente"
description: "Viaggio nel mondo delle lingue, ma con metodo: routine brevi e strumenti testati."
url: "https://nausica-c.github.io"
baseurl: "/FluenteMente"
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
 
